name: Build and create the VSIX for aXAML AutoCompetion extension 

on: 
  push: 
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Configure dotnet
        uses: actions/setup-dotnet@v2

      - name: Compile the LanguageServer (dotnet)
        run: dotnet build --configuration Release --output libs/ Avalonia.AXAML.LanguageServer/Avalonia.AXAML.LanguageServer 

      - name: Setup the NPM enviroment to compile the extension
        uses: actions/setup-node@v3
        with: 
          node-version: '16'

      - name: Install all NPM dependencies
        run: npm install

      - name: Create the release version of the extension
        uses: lannonbr/vsce-action@3.0.0
        with: 
          args: "package"
        
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with: 
          name: VSCode extension
          path: ./avalonia-axamlautocompletion-0.0.1.vsix

      - name: Create GitHub release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secreats.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}